openapi: 3.0.0
info:
  description: This is an API that shares recipes
  version: "1.0.0"
  title: Recipe App API

paths:
  # /login:
  #   post:
  #     tags:
  #      - Login
  #     x-controller: login
  #     x-operation: tryLogin
  #     summary: login the user
  #     security:
  #       - basicAuth: []
  #     description: try to login a user
  #     responses:
  #       201:
  #         description: login successful
  #         headers:
  #           Location:
  #             schema:
  #               type: string
  #       400:
  #         description: 'invalid input, object invalid'
  #       401:
  #       description: 'login unsuccesful'
  #       409:
  #         description: an existing account already exists
  /accounts:
    put:
      tags:
       - Accounts
      x-controller: accounts
      x-operation: authenticateAccount
      summary: authenticates an account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/accounts'
        description: Account to auth
      responses:
        200:
          description: account authenticated
          headers:
            Location:
              schema:
                type: string
        400:
          description: 'invalid input, object invalid'

    post:
      tags:
       - Accounts
      x-controller: accounts
      x-operation: createAccount
      summary: adds an account
      security:
        - Bearer: []
      description: Adds an account to the system
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/accounts'
        description: Account to add
      responses:
        201:
          description: account created
          headers:
            Location:
              schema:
                type: string
        400:
          description: 'invalid input, object invalid'
        409:
          description: an existing account already exists
  /accounts/{username}:
    parameters:
      - $ref: '#/components/parameters/PathUsername'
    get:
      tags:
       - Accounts
      x-controller: accounts
      x-operation: findAccount
      summary: searches accounts
      security:
        - Bearer: []
      description: |
        By passing in the appropriate options, you can search for
        a user in the system
      responses:
        200:
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/accounts'
        400:
          description: bad input parameter
    delete:
      tags:
       - Accounts
      security:
        - Bearer: []
      x-controller: accounts
      x-operation: deleteAccount
      summary: deletes an account
      description: deletes an account in the system
      responses:
        204:
         description: Deleted
        401:
          description: Unathorized
        403:
          description: Forbidden
        500:
          description: Internal Server Error
    put:
      tags:
       - Accounts
      x-controller: accounts
      x-operation: updateAccount
      summary: edits an account
      security:
        - Bearer: []
      description: edits an account in the system
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/accounts'
        description: Account to edit
      responses:
        200:
          description: account edited
        401:
          description: Unathorized
        403:
          description: Forbidden
        404:
          description: Not found
        500:
          description: Internal Server Error
          
  /recipe:
    get:
      tags:
        - All
      summary: list all recipes from user
      security:
        - Bearer: []
      x-controller: recipes
      x-operation: getAll
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/recipeList'
        400:
          description: bad input parameter
      
  /recipe/{recipeId}:
    parameters:
       - $ref: '#/components/parameters/RecipeId'
    post: 
      tags:
       - Recipes
      summary: create a new recipe
      security:
        - Bearer: []
      x-controller: recipes
      x-operation: addRecipe
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/recipe'
      responses:
        204:
          description: recipe added
          headers:
            Location:
              schema:
                type: string
        400:
          description: 'invalid input, object invalid'
        409:
          description: an existing recipe already exists
    get:
      summary: get specific recipe info
      tags:
        - Recipes
      security:
        - Bearer: []
      x-controller: recipes
      x-operation: getRecipe
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/recipe'
        '400':
          description: bad input parameter
    put:
      summary: Update recipe
      tags:
       - Recipes
      x-controller: recipes
      x-operation: updateRecipe
      security:
        - Bearer: []
      requestBody:
        $ref: '#/components/requestBodies/Recipe'
      responses:
        200:
          description: Success
        401:
          description: Unathorized
        403:
          description: Forbidden
        404:
          description: Not found
        500:
          description: Internal Server Error
    delete:
      summary: Delete recipe
      tags:
       - Recipes
      x-controller: recipes
      x-operation: deleteRecipe
      security:
        - Bearer: []
      responses:
        204:
          description: Success
        401:
          description: Unathorized
        403:
          description: Forbidden
        500:
          description: Internal Server Error
  /recipe/{recipeId}/ingridients:
    parameters:
       - $ref: '#/components/parameters/RecipeId'
    get:
      summary: Get ingridients in recipe
      tags:
        - Ingridients
      security:
        - Bearer: []
      x-controller: ingridients
      x-operation: getAll
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ingridients'
        '400':
          description: bad input parameter
  /recipe/{recipeId}/ingridients/{ingridientId}:
    parameters:
       - $ref: '#/components/parameters/RecipeId'
       - $ref: '#/components/parameters/IngridientId'
    get:
      summary: Get ingridients in recipe
      tags:
        - Ingridients
      security:
        - Bearer: []
      x-controller: ingridients
      x-operation: getIngridients
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ingridients'
        '400':
          description: bad input parameter
    post:
      summary: Add ingridients in recipe
      tags:
        - Ingridients
      security:
        - Bearer: []
      x-controller: ingridients
      x-operation: addIngridients
      requestBody:
        $ref: '#/components/requestBodies/Ingridient'
      responses:
        '201':
          description: Success
          headers:
            Location:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ingridients'
        '400':
          description: bad input parameter
    put:
      summary: Update recipe
      tags:
       - Ingridients
      x-controller: ingridients
      x-operation: updateIngridients
      security:
        - Bearer: []
      requestBody:
        $ref: '#/components/requestBodies/Ingridient'
      responses:
        200:
          description: Success
        401:
          description: Unathorized
        403:
          description: Forbidden
        404:
          description: Not found
        500:
          description: Internal Server Error
    delete:
      summary: Delete recipe
      tags:
       - Ingridients
      x-controller: ingridients
      x-operation: deleteIngridients
      security:
        - Bearer: []
      responses:
        204:
          description: Success
        401:
          description: Unathorized
        403:
          description: Forbidden
        500:
          description: Internal Server Error
  /recipe/{recipeId}/images{imageId}:
    parameters:
       - $ref: '#/components/parameters/RecipeId'
       - $ref: '#/components/parameters/ImageId'
    post:
      tags:
       - Images
      security:
        - Bearer: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/images'
      responses:
        '201':
          description: image added
          headers:
            Location:
              schema:
                type: string
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: an existing image already exists
    delete:
      summary: Delete image
      tags:
       - Images
      responses:
        204:
          description: Success
        401:
          description: Unathorized
        403:
          description: Forbidden
        500:
          description: Internal Server Error
components:
  parameters:
    PathUsername:
      name: username
      in: path
      required: true
      schema:
        type: string
    RecipeListId:
      name: recipeListId
      in: path
      required: true
      schema:
        type: string
    RecipeId:
      name: recipeId
      in: path
      required: true
      schema:
        type: string
    IngridientId:
      name: ingridientId
      in: path
      required: true
      schema:
        type: string
    ImageId:
      name: imageId
      in: path
      required: true
      schema:
        type: string
  requestBodies:
      Recipe:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/recipe'
      Ingridient:
        content:
            application/json:
              schema:
                $ref: '#/components/schemas/ingridients'
  schemas:
    recipeList:
      type: object
      properties:
        id:
          type: string
          readOnly: true
        recipes:
          type: object
          properties:
            recipeslist:
              type: array
              items:
                $ref: '#/components/schemas/recipe'
    recipe:
      type: object
      properties:
        id: 
          type: string
          readOnly: true
        name: 
          type: string
        rating:
          type: integer
        description:
          type: string
        season:
          type: string
        ingridients:
          type: object
          properties:
            ingridientsList:
              type: array
              items:
                $ref: '#/components/schemas/ingridients'
         
    ingridients:
      type: object
      properties:
        ingridientId:
          type: string
        name:
          type: string
        amount:
          type: integer
        season:
          type: string
          
    images:
      type: object
      properties:
        image:
          type: string
          format: byte
        imageId:
          type: string
        recipeId:
          type: string
          
    accounts:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
          writeOnly: true
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/IT-Foodies/recipe-box/1.0.0